# ndarray的创建
### 1.基础构造:                 适用于手动构造小规模数组/复制已有数据
### 2.预定义形状填充:            用于快速初始化固定形状的数组(如全0占位，全1初始化)
### 3.基于数值范围生成:          生成数值序列，常用与模拟时间序列，坐标网格等
### 4.特殊矩阵生成:             数学运算专用(如单位矩阵)
### 5.随机数组生成:             模拟实验数据，初始化神经网络权重等场景
### 6.高级构造方法:             处理非结构化数据(如文件，字符串)或通过函数生成复杂数组


In [3]:
import numpy as np
# 1.基础的创建方法
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [7]:
# 2.预定义形状
# 全0 全1 未初始化 固定值
# 全0
arr1 = np.zeros((2,3))
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [8]:
# 全1
arr2 = np.ones((5,8))
print(arr2)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [10]:
# 固定值
arr3 = np.full((3,4),2026)
print(arr3)

[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [13]:
# 3.等差数列
arr4 = np.arange(0,20,2)    # start,end,step
print(arr4)

[ 0  2  4  6  8 10 12 14 16 18]


In [14]:
# 等间隔数列
arr5 = np.linspace(0,20,9)  #start,end,count
print(arr5)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20. ]


In [20]:
# 4.特殊矩阵生成
# 0矩阵 所有元素为0
# 单位矩阵 对角线为1，其他为0
# 对角矩阵 只有对角线上的非0
# 对称矩阵 A = A^T

# 单位矩阵
arr = np.eye(3,dtype=int)
print("单位矩阵")
print(arr)
print('\n')

# 对角矩阵(主对角线上的非0，其他为0)
arr2 = np.diag([5,1,2,3])   # 主对角线上的数字
print("对角矩阵")
print(arr2)
print('\n')

单位矩阵
[[1 0 0]
 [0 1 0]
 [0 0 1]]


对角矩阵
[[5 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]




In [28]:
# 5.随机数组的生成
# 生成0-1之间的随机浮点数(均匀分布)
arr = np.random.rand(2,3)
print(arr)
print('\n')

# 生成指定范围区间的随机浮点数
arr2 = np.random.uniform(3,6,(2,3))
print(arr2)
print('\n')

# 生成正态分布的随机数列
arr = np.random.randn(2,3)
print(arr)

[[0.83839373 0.89623196 0.27165303]
 [0.47872359 0.84552259 0.69755236]]


[[3.07284417 3.22653008 4.44897182]
 [5.31714129 3.68850169 4.05717323]]


[[ 0.27510941  2.09263325 -0.99037354]
 [-0.10685798 -1.17546075  0.16690188]]


In [34]:
# 设置随机种子
np.random.seed(20)
arr = np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]
