# ndarray的运算

In [1]:
import numpy as np
# 算术运算
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [2]:
# 二维
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
b = np.array([[4, 5, 6],[7, 8, 9],[1,2,3]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]
[[       1       32      729]
 [   16384   390625 10077696]
 [       7       64      729]]


In [4]:
# 数组与标量运算
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(a+3)
print(a*3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [5]:
# 矩阵乘法
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
b = np.array([[4, 5, 6],[7, 8, 9],[1,2,3]])
print(a @ b)

[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]
