In [2]:
# 平方根
import numpy as np
print(np.sqrt(9))
arr = np.array([1,4,9])
print(np.sqrt(arr))

3.0
[1. 2. 3.]


In [3]:
# 指数
print(np.exp(1)) # e的1次方

2.718281828459045


In [5]:
# 自然对数 lnX
print(np.log(2.718281828459045))

1.0


In [9]:
# sin cos
print(np.sin(np.pi/2))
print(np.cos(np.pi))

1.0
-1.0


In [10]:
# 绝对值
arr = np.array([1,-4,-9,16])
print(np.abs(arr))

[ 1  4  9 16]


In [11]:
# 计算a的b次幂
print(np.power(arr,2))

[  1  16  81 256]


In [12]:
# 四舍五入
print(np.round(3.66))

4.0


In [14]:
# 向上取整，向下取整
arr = np.array([1.6,4.7,9.8,16.9])
print(np.ceil(arr))     # 向上
print(np.floor(arr))    # 向下

[ 2.  5. 10. 17.]
[ 1.  4.  9. 16.]


In [15]:
# 检测缺失值
np.isnan([1,2,3,np.nan,6,3,8])

array([False, False, False,  True, False, False, False])